### ISSUE TITLE
QR Code Reader Alignment Incorrect

### ISSUE THREAD

**Issue by Happs80** [ReliefApplications/bms_vendor_app#52]
On android phone with 1080 x 2160 pixels resolution, the QR code reader panel is locked bottom left.

**Comment by barbaraReliefapps** [comment]
Check on various devices. Probably related to the device itself, not the app

**Comment by Happs80** [comment]
Sure, but we still need to solve. The android device tested is a common resolution.

**Comment by Happs80** [comment]
Oh. I just found maybe the cause. When i held my phone in portrait mode, it was centred.

So the qr code scanner needs to fixed to landscape, or people will be forced to switch back and forth.

possible?

**Comment by barbaraReliefapps** [comment]
I have tried on different devices and it always appeared centered

**Comment by Happs80** [comment]
Landscape now. Great.
