### ISSUE TITLE
QR Code Scanner Error - High

### ISSUE THREAD

**Issue by Happs80** [ReliefApplications/bms_vendor_app#64]
This error has returned.

Can we not fix the scanner in the middle of the landscape view?)

https://github.com/ReliefApplications/bms_vendor_app/issues/52

![image](https://user-images.githubusercontent.com/31128624/59224653-35495400-8bcf-11e9-8ad8-5f3e997620e7.png)

**Comment by barbaraReliefapps** [comment]
This was linked to the device mode (landscape or portrait) itself, not much we can do on the app

**Comment by Happs80** [comment]
But i don't understand. If the app can force landscape mode, then why not the scanner?

**Comment by Happs80** [comment]
Never mind. It appears as centered on my phone now. And also on others. Can close for now.
